/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Calcu */

#ifndef _Included_Calcu
#define _Included_Calcu
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Calcu
 * Method:    suma
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Calcu_suma
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Calcu
 * Method:    resta
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Calcu_resta
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Calcu
 * Method:    multi
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Calcu_multi
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Calcu
 * Method:    divi
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_Calcu_divi
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
